# -*- coding: utf-8 -*-
"""Kiểm thử tự động dashboard ĐGNK PVEP (Playwright, Chromium).
Chạy: python tools/test_app.py [thư_mục_chụp_màn_hình]"""
import json, csv, io, sys, pathlib, shutil, tempfile
from playwright.sync_api import sync_playwright
ROOT = pathlib.Path(__file__).resolve().parent.parent
URL = (ROOT / 'index.html').as_uri()
SHOT = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else None
R = []
def rec(i, name, ok, detail=''):
    R.append((i, name, 'ĐẠT' if ok else 'KHÔNG ĐẠT', str(detail))); print(i, 'OK ' if ok else 'FAIL', name, detail)
def read_dl(d): return list(csv.reader(io.StringIO(open(d.value.path(), encoding='utf-8-sig').read())))
DATA = json.loads((ROOT / 'data' / 'data.js').read_text(encoding='utf-8').split('window.APP_DATA = ', 1)[1].rstrip().rstrip(';'))
TT = DATA['thu_tuc']; OKL = ('ĐÃ XÁC MINH', 'NGHIỆP VỤ NỘI BỘ')
with sync_playwright() as p:
    b = p.chromium.launch(); ctx = b.new_context(viewport={'width': 1440, 'height': 900}, accept_downloads=True)
    pg = ctx.new_page(); errs = []; pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto(URL + '#tong-quan'); pg.wait_for_timeout(700)
    k = pg.locator('#kpis .kpi .v').all_inner_texts()
    rec('KT01', 'Tải trang, 5 chỉ số KPI khớp dữ liệu', len(k) == 5 and int(k[0]) == len(TT) and int(k[1]) == sum(t['nhan_xac_minh'] == 'ĐÃ XÁC MINH' for t in TT), 'KPI=' + ','.join(k))
    rec('KT02', 'Không lỗi JavaScript khi tải', not errs, ';'.join(errs))
    rec('KT03', 'Phân loại Mô hình 1/2 hiển thị đầu trang', pg.locator('.models .model').count() == 2 and 'Điều 52' in pg.locator('.models').inner_text())
    rec('KT04', 'Hướng dẫn nhanh: 5 câu hỏi và bảng phân biệt khái niệm', pg.locator('.qa .card').count() == 5 and 'không được đánh đồng' in pg.locator('#v-tong-quan').inner_text())
    rec('KT05', 'Nhãn bộ dữ liệu hiển thị', 'công khai' in pg.locator('#boBadge').inner_text() or 'NỘI BỘ' in pg.locator('#boBadge').inner_text(), pg.locator('#boBadge').inner_text())
    pg.select_option('#fOverview select[data-k="nhanh"]', '2'); pg.wait_for_timeout(150)
    rec('KT06', 'Lọc theo giai đoạn cập nhật KPI', pg.locator('#kpis .kpi .v').first.inner_text() == str(sum(t['nhanh'] == '2' for t in TT)))
    pg.select_option('#fOverview select[data-k="nhanh"]', ''); pg.select_option('#fOverview select[data-k="tt"]', 'CẦN XÁC MINH'); pg.wait_for_timeout(150)
    rec('KT07', 'Lọc theo nhãn xác minh', pg.locator('#kpis .kpi .v').first.inner_text() == str(sum(t['nhan_xac_minh'] == 'CẦN XÁC MINH' for t in TT)))
    pg.select_option('#fOverview select[data-k="tt"]', '')
    rec('KT08', '05 việc ưu tiên và cổng quyết định gần nhất', pg.locator('#prio li').count() == 5 and pg.locator('#gates li').count() == 3)
    pg.locator('.qa button[data-p="TT-1.7"]').click(); pg.wait_for_timeout(200)
    rec('KT09', 'Liên kết trong Hướng dẫn nhanh mở chi tiết thủ tục', 'nội bộ' in pg.locator('#dTitle').inner_text()); pg.keyboard.press('Escape')
    # sơ đồ
    pg.goto(URL + '#ban-do'); pg.wait_for_timeout(300)
    n = pg.locator('#tree g.node').count()
    rec('KT10', 'Sơ đồ cây đủ nút (thủ tục + 6 cổng)', n == len(TT) + 6, f'{n} nút')
    grp = pg.locator('#tree g.grp').evaluate_all('e=>e.map(x=>x.textContent)')
    rec('KT11', 'Nhánh 3 rẽ hai luồng A/B; Nhánh 4 tách ngoài khơi/trên bờ', len(grp) == 6 and any('Luồng A' in g for g in grp) and any('Luồng B' in g for g in grp) and any('ngoài khơi' in g.lower() for g in grp) and any('trên bờ' in g.lower() for g in grp), ' | '.join(g.replace('\n', ' ') for g in grp))
    pg.locator('#tree g.node[data-p="TT-3.2"]').click(); pg.wait_for_timeout(250)
    body = pg.locator('#dBody').inner_text()
    rec('KT12', 'Chi tiết hiển thị luồng, điều kiện tiên quyết, căn cứ, thẻ văn bản', 'Luồng A' in body and 'Điều kiện tiên quyết' in body and 'TT-3.1' in body and 'Căn cứ pháp lý' in body and '11/12/2025' in body)
    pg.locator('#dBody button[data-p="TT-3.1"]').first.click(); pg.wait_for_timeout(200)
    rec('KT13', 'Bấm mã điều kiện tiên quyết chuyển sang thủ tục đó', pg.locator('#dCode').inner_text().startswith('TT-3.1')); pg.keyboard.press('Escape')
    pg.locator('#tree g.branch[data-b="4"]').click(); pg.wait_for_timeout(200)
    n4 = sum(t['nhanh'] == '4' for t in TT) + 1
    rec('KT14', 'Thu gọn nhánh 4', pg.locator('#tree g.node').count() == len(TT) + 6 - n4)
    pg.click('#expandAll'); pg.wait_for_timeout(150)
    pg.locator('#tree g.branch[data-b="1"]').focus(); pg.keyboard.press('Enter'); pg.wait_for_timeout(150)
    rec('KT15', 'Điều khiển bằng bàn phím (Enter thu gọn nhánh 1)', pg.locator('#tree g.branch[data-b="1"]').get_attribute('aria-expanded') == 'false')
    pg.click('#expandAll'); pg.wait_for_timeout(150)
    pg.select_option('#fTree select[data-k="ut"]', 'Cao'); pg.wait_for_timeout(150)
    rec('KT16', 'Nút không khớp bộ lọc được làm mờ', pg.locator('#tree g.node.dim').count() == sum(t['uu_tien'] != 'Cao' for t in TT))
    pg.select_option('#fTree select[data-k="ut"]', '')
    pg.locator('#tree g.node[data-g="G3"]').click(); pg.wait_for_timeout(150)
    rec('KT17', 'Mở chi tiết cổng quyết định', 'liên danh' in pg.locator('#dTitle').inner_text()); pg.keyboard.press('Escape')
    # danh mục
    pg.goto(URL + '#danh-muc'); pg.wait_for_timeout(250)
    rec('KT18', 'Danh mục 16 cột (15 cột yêu cầu + quan hệ trình tự)', pg.locator('#tCat thead th').count() == 16)
    pg.fill('#qCat', 'Điều 30 NĐ 58'); pg.wait_for_timeout(200)
    codes = pg.locator('#tCat tbody tr.clk').evaluate_all('r=>r.map(x=>x.dataset.p)')
    rec('KT19', 'Tìm kiếm theo căn cứ “Điều 30 NĐ 58”', 'TT-3.4' in codes, ','.join(codes))
    pg.fill('#qCat', 'zzzkhongco'); pg.wait_for_timeout(150)
    rec('KT20', 'Không có kết quả thì hiện thông báo', 'Không có thủ tục' in pg.locator('#tCat').inner_text())
    pg.fill('#qCat', ''); pg.select_option('#fCat select[data-k="ut"]', 'Cao'); pg.wait_for_timeout(150)
    nc = pg.locator('#tCat tbody tr.clk').count()
    with pg.expect_download() as d: pg.click('#expCatalog')
    rows = read_dl(d)
    rec('KT21', 'Xuất CSV danh mục đang lọc (UTF-8 tiếng Việt)', len(rows) - 1 == nc and 'Tên thủ tục/đầu việc' in rows[0], f'{nc} dòng')
    pg.select_option('#fCat select[data-k="ut"]', '')
    pg.locator('#tCat tbody tr.clk').first.click(); pg.wait_for_timeout(150)
    rec('KT22', 'Bấm dòng danh mục mở chi tiết', pg.locator('#drawer.on').count() == 1); pg.keyboard.press('Escape')
    # ma trận
    pg.goto(URL + '#ma-tran'); pg.wait_for_timeout(250)
    rec('KT23', 'Cảnh báo văn bản sửa đổi, chưa kiểm chứng, thiếu liên kết', pg.locator('#vbAlerts .alert').count() == 3)
    rec('KT24', 'Có liên kết nguồn chính thức cho văn bản đã tra cứu', pg.locator('#mBody a[href*="vbpl.vn"], #mBody a[href*="quochoi.vn"], #mBody a[href*="moit.gov.vn"]').count() > 0)
    pg.click('#mTabs button[data-t="cmp"]'); pg.wait_for_timeout(150)
    rec('KT25', 'So sánh “Quy định đã rõ” và “Khoảng trống”', pg.locator('.cmp .col').count() == 2, pg.locator('#cntMat').inner_text())
    pg.click('#mTabs button[data-t="docs"]'); pg.fill('#qMat', 'Dầu khí'); pg.wait_for_timeout(150)
    rec('KT26', 'Tìm văn bản trong danh mục văn bản', pg.locator('#mBody tbody tr').count() >= 2); pg.fill('#qMat', '')
    with pg.expect_download() as d: pg.click('#expVerify')
    rows = read_dl(d)
    rec('KT27', 'Xuất danh sách CẦN XÁC MINH', len(rows) > 10 and rows[0][0] == 'Loại', f'{len(rows) - 1} nội dung')
    # rủi ro
    pg.goto(URL + '#rui-ro'); pg.wait_for_timeout(250)
    rec('KT28', 'Bảng rủi ro đủ 13 trường; bản đồ nhiệt đủ mã', pg.locator('#tRisk thead th').count() == 13 and pg.locator('#heat button').count() == len(DATA['rui_ro']))
    pg.select_option('#fRGroup', 'Dữ liệu'); pg.wait_for_timeout(150)
    rec('KT29', 'Lọc rủi ro theo nhóm', pg.locator('#tRisk tbody tr').count() == sum(r['nhom'] == 'Dữ liệu' for r in DATA['rui_ro']))
    with pg.expect_download() as d: pg.click('#expAsk1')
    rows = read_dl(d); caps = {r[0] for r in rows[1:]}
    rec('KT30', 'Xuất “Nội dung cần xin ý kiến Lãnh đạo PVEP/Petrovietnam”', len(rows) > 1 and caps <= {'PVEP', 'Petrovietnam'}, f'{len(rows) - 1} nội dung')
    # lộ trình
    pg.goto(URL + '#ke-hoach'); pg.wait_for_timeout(250)
    rec('KT31', 'Kanban 4 cột, đủ thẻ', pg.locator('.kcol').count() == 4 and pg.locator('.kcard').count() == len(DATA['ke_hoach']))
    pg.click('#pTabs button[data-t="gantt"]'); pg.wait_for_timeout(150)
    rec('KT32', 'Bảng tiến độ có thanh thời gian', pg.locator('#pBody svg').count() == len(DATA['ke_hoach']))
    pg.click('#pTabs button[data-t="over"]'); pg.wait_for_timeout(150)
    rec('KT33', 'Danh sách quá hạn hoạt động', pg.locator('#pBody').inner_text() != '')
    # vai trò, nhật ký
    pg.goto(URL + '#danh-muc'); pg.locator('#tCat tbody tr.clk').first.click(); pg.wait_for_timeout(150)
    rec('KT34', 'Người xem không thấy khung cập nhật', pg.locator('#eSave').count() == 0); pg.keyboard.press('Escape')
    pg.select_option('#role', 'editor'); pg.fill('#who', 'Kiểm thử'); pg.locator('#who').dispatch_event('change')
    pg.goto(URL + '#ke-hoach'); pg.click('#pTabs button[data-t="kanban"]'); pg.wait_for_timeout(150)
    before = pg.locator('.kcol').nth(1).locator('.kcard').count()
    pg.select_option('select[data-kh="KH01"]', 'Đang thực hiện'); pg.wait_for_timeout(200)
    rec('KT35', 'Người cập nhật đổi tình trạng công việc', pg.locator('.kcol').nth(1).locator('.kcard').count() == before + 1)
    pg.goto(URL + '#danh-muc'); pg.locator('#tCat tbody tr[data-p="TT-1.1"]').click(); pg.wait_for_timeout(150)
    pg.select_option('#eLg', 'ĐÃ XÁC MINH'); pg.fill('#eNote', 'Thử nghiệm'); pg.click('#eSave'); pg.wait_for_timeout(200); pg.keyboard.press('Escape')
    pg.goto(URL + '#quan-tri'); pg.wait_for_timeout(150)
    lg = pg.locator('#tLog').inner_text()
    rec('KT36', 'Nhật ký ghi người sửa, thời gian, giá trị cũ và mới', 'Kiểm thử' in lg and 'nhan_xac_minh' in lg and 'KH01' in lg)
    rec('KT37', 'Người cập nhật không được nhập tệp', pg.locator('#impBtn').is_disabled())
    pg.select_option('#role', 'admin'); pg.wait_for_timeout(150)
    pg.set_input_files('#impFile', str(ROOT / 'data' / 'ke_hoach.csv')); pg.select_option('#impTable', 'ke_hoach'); pg.click('#impBtn'); pg.wait_for_timeout(300)
    rec('KT38', 'Quản trị viên nhập CSV hợp lệ', 'Đã nhập' in pg.locator('#impMsg').inner_text())
    bad = pathlib.Path(tempfile.gettempdir()) / 'bad_test.csv'; bad.write_text('ma,nhiem_vu\nX1,a\n', encoding='utf-8')
    pg.set_input_files('#impFile', str(bad)); pg.click('#impBtn'); pg.wait_for_timeout(200)
    rec('KT39', 'Từ chối CSV sai cấu trúc', 'thiếu cột' in pg.locator('#impMsg').inner_text())
    pg.on('dialog', lambda dd: dd.accept()); pg.click('#resetLocal'); pg.wait_for_timeout(200)
    pg.goto(URL + '#tong-quan'); pg.wait_for_timeout(150)
    rec('KT40', 'Xóa thay đổi cục bộ, trở về dữ liệu gốc', pg.locator('#kpis .kpi .v').nth(1).inner_text() == k[1])
    pg.click('#zPlus'); pg.click('#zPlus'); pg.click('#zPlus'); pg.click('#zPlus'); pg.click('#zPlus'); pg.click('#zPlus')
    fs = pg.evaluate("getComputedStyle(document.documentElement).fontSize")
    rec('KT41', 'Phóng chữ tối đa 150% (cỡ gốc 17px)', fs == '25.5px', fs)
    pg.click('#zReset')
    if SHOT:
        for v in ['tong-quan', 'ban-do', 'danh-muc', 'ma-tran', 'rui-ro', 'ke-hoach']:
            pg.goto(URL + '#' + v); pg.wait_for_timeout(250); pg.screenshot(path=str(SHOT / f'{v}.png'))
        pg.goto(URL + '#ban-do'); pg.wait_for_timeout(200)
        pg.locator('#tree g.branch[data-b="3"]').scroll_into_view_if_needed(); pg.wait_for_timeout(200); pg.screenshot(path=str(SHOT / 'nhanh3.png'))
        pg.locator('#tree g.node[data-p="TT-3.2"]').click(); pg.wait_for_timeout(300); pg.screenshot(path=str(SHOT / 'chi_tiet.png'))
    # điện thoại
    m = b.new_context(viewport={'width': 390, 'height': 844}).new_page(); m.on('pageerror', lambda e: errs.append(str(e)))
    m.goto(URL + '#tong-quan'); m.wait_for_timeout(500)
    sw = m.evaluate('document.documentElement.scrollWidth')
    rec('KT42', 'Điện thoại: không tràn ngang, có nút menu và logo', sw <= 392 and m.locator('#menuBtn').is_visible() and m.locator('.mlogo').is_visible(), f'scrollWidth={sw}')
    m.click('#menuBtn'); m.wait_for_timeout(300); m.click('.side nav a[data-v="ban-do"]'); m.wait_for_timeout(300)
    rec('KT43', 'Điện thoại: mở menu, chuyển phân hệ, menu tự đóng', m.locator('#v-ban-do.on').count() == 1 and 'open' not in (m.locator('.side').get_attribute('class') or ''))
    if SHOT: m.goto(URL + '#tong-quan'); m.wait_for_timeout(300); m.screenshot(path=str(SHOT / 'dien_thoai.png'))
    rec('KT44', 'Không lỗi JavaScript trong toàn bộ phiên kiểm thử', not errs, ';'.join(errs))
    b.close()
ok = sum(r[2] == 'ĐẠT' for r in R); print(f'{ok}/{len(R)}')
json.dump(R, open(pathlib.Path(tempfile.gettempdir()) / 'test_results.json', 'w', encoding='utf-8'), ensure_ascii=False)
